POST https://3001-twbluenaxel-phonebookba-xy4mblpdbat.ws-us54.gitpod.io/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "hi",
    "number": "7022339299"
}

###
GET https://3001-twbluenaxel-phonebookba-xy4mblpdbat.ws-us54.gitpod.io/api/persons